### ISSUE TITLE
Multi-class multi-object pose estimation ?

### ISSUE THREAD

**Issue by wusuoweima** [LinHuang17/NCF-code#2]
Does this method only estimate the position of one object after each training session?

Can this method achieve multi-class multi-object pose estimation?

**Comment by LinHuang17** [comment]
Hello,

For the current version of our method, it is designed to handle a single instance of a single object. 

The method could be extended to handle multiple instances of the same object, e.g., (1) by using the Progressive-X multi-instance fitting scheme [1], as in EPOS [2], or (2) by detecting the instances by a 2D object detector and applying the proposed method to the detected regions.

Training a single network for multiple objects and extending the method to object categories is the focus of our future work.

[1] Barath, D., Matas, J.: Progressive-X: Efficient, anytime, multi-model fitting algorithm. ICCV (2019)
[2] Hodan, T., Barath, D., Matas, J.: EPOS: Estimating 6D pose of objects with symmetries. CVPR (2020)
