### ISSUE TITLE
about arguments such as wks_size and wks_z_shift

### ISSUE THREAD

**Issue by lyj9494** [LinHuang17/NCF-code#3]
Hello! Thanks for sharing your work!
After reading the code, I’m curious about how to set the value of arguments such as `bbx_size`, `bbx_shift`, `wks_size`, `wks_z_shift`, `test_wks_size`, and `test_wks_z_shift`. Are they same for all instances in different scenes?

**Comment by LinHuang17** [comment]
Hello,

`bbx_size` decides the size of a bounding volume (e.g., box, sphere) centered around the target object model (`bbx_shift` can be ignored for this case). Values can be set as long as the volume can encapsulate the object.

`wks_size` & `wks_z_shift` decide the 3D space which NCF models in front of the camera during training, while `test_wks_size` & `test_wks_z_shift` decide the 3D space modeled during testing.

These parameters also decide where NCF samples 3D query points during training or testing. Please also check both sections: `Sampling 3D Query Points` & `Method Parameters` in the paper for more details.
